In [1]:
### Q1. Create an array having consecutive natural numbers of size 6x3 and print it. 

In [19]:
import numpy as np


In [20]:
arr_natural = np.arange(18).reshape(6,3)
print(f"The consecutive array is\n{arr_natural}.")

The consecutive array is
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]].


In [26]:
import pandas as pd

data_url = r'/Users/rishwari/Desktop/Studies/Machine Learning/Breast-Cancer-Detection-using-Machine-Learning-master/WeekOneDataset.xlsx'
df = pd.read_excel(data_url)
print(df)

  Name  Income per month          State  Age Sex  Number of siblings
0    A                50     Tamil Nadu   23   M                   0
1    B                34      Karnataka   37   F                   3
2    C                54     Tamil Nadu   35   F                   1
3    D                24  Uttar Pradesh   26   F                   4
4    E                19          Bihar   59   M                   5
5    F                21          Bihar   48   M                   6
6    G                40          Delhi   30   F                   2
7    H                20  Uttar Pradesh   72   M                  10
8    I                30      Telangana   22   F                   0
9    J                18    Chattisgarh   42   M                   7


In [27]:
df


Name  Income per month          State  Age Sex  Number of siblings
0    A                50     Tamil Nadu   23   M                   0
1    B                34      Karnataka   37   F                   3
2    C                54     Tamil Nadu   35   F                   1
3    D                24  Uttar Pradesh   26   F                   4
4    E                19          Bihar   59   M                   5
5    F                21          Bihar   48   M                   6
6    G                40          Delhi   30   F                   2
7    H                20  Uttar Pradesh   72   M                  10
8    I                30      Telangana   22   F                   0
9    J                18    Chattisgarh   42   M                   7

In [28]:
## Q2: Rename alll the columns in the dataset as per your wish and save it in another dataframe and name it df2


In [30]:
df2 = df.rename(columns={"Name":"Name_Patient","Income per month" : "Monthly Income","State":"Name of State ","Age":"Age of Patient","Sex":"Gender","Number of siblings":"Siblings"})

In [32]:
df2


Name_Patient  Monthly Income Name of State   Age of Patient Gender  Siblings
0            A              50     Tamil Nadu              23      M         0
1            B              34      Karnataka              37      F         3
2            C              54     Tamil Nadu              35      F         1
3            D              24  Uttar Pradesh              26      F         4
4            E              19          Bihar              59      M         5
5            F              21          Bihar              48      M         6
6            G              40          Delhi              30      F         2
7            H              20  Uttar Pradesh              72      M        10
8            I              30      Telangana              22      F         0
9            J              18    Chattisgarh              42      M         7

## Q4: Show only the columns information, sex and number of siblings. 


In [36]:
df[["Sex","Number of siblings"]]

Sex  Number of siblings
0   M                   0
1   F                   3
2   F                   1
3   F                   4
4   M                   5
5   M                   6
6   F                   2
7   M                  10
8   F                   0
9   M                   7

In [38]:
## Q5: Use iloc method to print data from column 1 to 4 and rows 3 to 9

In [37]:
df2.iloc[3:10,1:5]

Monthly Income Name of State   Age of Patient Gender
3              24  Uttar Pradesh              26      F
4              19          Bihar              59      M
5              21          Bihar              48      M
6              40          Delhi              30      F
7              20  Uttar Pradesh              72      M
8              30      Telangana              22      F
9              18    Chattisgarh              42      M

In [39]:
## Q6: Find the total value count of number of siblings in the given dataset

In [42]:
df["Number of siblings"].value_counts()

0     2
10    1
7     1
6     1
5     1
4     1
3     1
2     1
1     1
Name: Number of siblings, dtype: int64

In [43]:
# Q7: What are dependent and independent varibles in our dataset? 

In [44]:
##Independent : Income Per Month , Name ,State_name ,Age  ,Sex  
#dependent : Number of siblings


In [45]:
## Q8: Mention all your finding from the above given heatmap. 

In [ ]:
#There exist a correlation between elements.
#There is correlation between income per to age and number of siblings per month.
#Correlation between number pf sibling sto age

